import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import NavbarWrapper from "@/components/provider/NavbarWrapper";
import SessionProviderWrapper from "@/components/provider/sessionProviderWraper";
import QueryProvider from "@/components/provider/Query-provider";
import { ThemeProvider } from "next-themes";
import RouteProgress from "@/components/provider/RoutePregress";
import ScrollToTopButton from "@/components/reusable/scrol-top-button";
import PageTracker from "@/app/service/page-tracer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "News Hub",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={false}
        >
          <QueryProvider>
            <SessionProviderWrapper>
              <NavbarWrapper />
              <RouteProgress />
              <ScrollToTopButton threshold={600} />
              <PageTracker />
              {children}
              <Toaster />
            </SessionProviderWrapper>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
